name: ci

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY: devops-showcase-api

jobs:
  build_test_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Test (Spring)
        working-directory: backend
        run: ./mvnw -q test

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::696817466202:role/devops-showcase-github-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image (API)
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG_SHA: sha-${{ github.sha }}
        run: |
          docker build -t $REGISTRY/${ECR_REPOSITORY}:latest -f backend/Dockerfile backend
          docker tag  $REGISTRY/${ECR_REPOSITORY}:latest $REGISTRY/${ECR_REPOSITORY}:$IMAGE_TAG_SHA
          docker push $REGISTRY/${ECR_REPOSITORY}:latest
          docker push $REGISTRY/${ECR_REPOSITORY}:$IMAGE_TAG_SHA