name: ci

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1
  ECR_API_REPOSITORY: devops-showcase-api
  ECR_FRONT_REPOSITORY: devops-showcase-front
  API_URL: https://cpdk2jfrxx.eu-west-1.awsapprunner.com

jobs:
  build_test_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Test (Spring)
        working-directory: backend
        run: |
          chmod +x mvnw
          ./mvnw -q test

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::696817466202:role/devops-showcase-github-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image (API)
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG_SHA: sha-${{ github.sha }}
        run: |
          set -euo pipefail
          IMAGE_LATEST="$REGISTRY/${ECR_API_REPOSITORY}:latest"
          IMAGE_SHA="$REGISTRY/${ECR_API_REPOSITORY}:${IMAGE_TAG_SHA}"

          echo "API IMAGE_LATEST=$IMAGE_LATEST"
          echo "API IMAGE_SHA=$IMAGE_SHA"

          docker build -t "$IMAGE_LATEST" -f backend/Dockerfile backend
          docker tag  "$IMAGE_LATEST" "$IMAGE_SHA"
          docker push "$IMAGE_LATEST"
          docker push "$IMAGE_SHA"

      - name: Build and push Docker image (FRONT)
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG_SHA: sha-${{ github.sha }}
        run: |
          set -euo pipefail
          IMAGE_LATEST="$REGISTRY/${ECR_FRONT_REPOSITORY}:latest"
          IMAGE_SHA="$REGISTRY/${ECR_FRONT_REPOSITORY}:${IMAGE_TAG_SHA}"

          echo "FRONT IMAGE_LATEST=$IMAGE_LATEST"
          echo "FRONT IMAGE_SHA=$IMAGE_SHA"
          echo "API_URL=${API_URL}"

          docker build \
            -t "$IMAGE_LATEST" \
            -t "$IMAGE_SHA" \
            --build-arg API_BASE_URL="${API_URL}" \
            -f frontend/Dockerfile frontend

          docker push "$IMAGE_LATEST"
          docker push "$IMAGE_SHA"

      - name: Trigger App Runner deployment (API)
        run: aws apprunner start-deployment --service-arn arn:aws:apprunner:eu-west-1:696817466202:service/devops-showcase-api/66a02c2bb10447e5b0b86e63264feb46

      - name: Trigger App Runner deployment (FRONT)
        run: aws apprunner start-deployment --service-arn arn:aws:apprunner:eu-west-1:696817466202:service/devops-showcase-front/2875112bc9e04e158091ae3902c535e5